### PR TITLE
Honey limiting

### PR DESCRIPTION
**Pull request by zeuner**
Bee hives currently make it easy to create resources for free just by repeatedly digging and placing them. This gives always some honey and another queen bee.

This patch adds some balance by introducing configurable delays after which the resources are generated.

### CODE REVIEW

**Comment by runsy** [comment]
I've implement some of your ideas:

- Behives now are crafted with Queen Bees (not Worker Bees)
- Behives drop from 1 to 6 Honeycombs max (not always 6).
- No initial honey when an artificial Beehive is placed.
- When a Behive is placed, it takes 300s to a Worker Bee being automatically created. (not inmediately)

If a Beehive is created by a Queen bee I think that it is OK that the Queen bee arises when its Beehive is destroyed. To avoid a infinite Queen Bee Creator now the Beehives are crafted only with Queen Bees.

**Comment by zeuner** [comment]
Thanks. I just tried it, but I think it still allows creating infinite queen bees since digging a beehive will still drop the beehive, and creates a queen bee in addition to that. So, I would argue that it still makes sense to at least have a delay for creating an extra queen bee, or not to drop a beehive that can just be placed again (forcing the player to craft another one using the queen bee).

**Comment by runsy** [comment]
You are right. I've updated. Now Beehive not dropped.

**Comment by zeuner** [comment]
Great, I like the logic as it is now, makes digging beehives a less arbitrary act. Will see how the bee population will evolve now...

**Pull request merged**
