### PR TITLE
properly manage the list of active mobs

### PR DESCRIPTION
**Pull request by fluxionary**
currently, kitz's list of active mobs is not maintained properly, grows to a huge size, with the result that calls to `kitz.get_nearby_entity` and `kitz.get_closest_entity` become enormously expensive, which is a huge problem because many mobs call those every "step"!

in general, maintaining such a list works, but it is not recommended. see https://github.com/minetest/minetest/blob/2854c19792a1c11c46788d15b746cf3762984a38/doc/lua_api.txt#L6823-L6834

### CODE REVIEW

**Comment by runsy** [comment]
I solved it creating an new _id field and then comparing.
```

local _id = 0

function kitz.logon_mob(self)
	_id = _id + 1
	kitz.active_mobs[_id] = self
	self._id = _id
end

function kitz.logout_mob(self)
	kitz.active_mobs[self._id] = nil
end
```

**Comment by fluxionary** [comment]
@runsy your fix is non-functional. if you're not storing values for the full sequence of "ids", you're still using a hash table, not an array. `ipairs` will stop working as soon as an index is removed. hashing numbers (double value) is also exactly as expensive as hashing userdata (pointer value).

**Comment by runsy** [comment]
Yes, youŕe right. Solved.

But take into account 2 things:
1.- In mobkit the mobs made a check every 16ms, if I could remember, in the surrounding nodes to take the mobs.
2.- With my implementation:
- The check is every 1 second and only if necessary for the function.
- The objects are set/removed in the activate/onactivate events so no problem with conflicts. Anyway I prefer to use ids.

Looping thru tables is not expensive at this scale, few mobs at the same time.

**Comment by fluxionary** [comment]
your current solution works, closing this.

**Pull request closed without merging**
